name: Update Plex Data

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    env:
      PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
      PLEX_URL: ${{ secrets.PLEX_URL }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install Dependencies
        run: composer install
        
      - name: Update Plex Data
        run: php fetchData.php
        
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/data/recent.json
          git commit -m "Update Plex data" || echo "No changes to commit"
          git push